### ISSUE TITLE
django-simple-captcha not in requirements.txt

### ISSUE THREAD

**Issue by jarrettchisholm** [hovel/pybbm_org#2]
`django-simple-captcha` not in requirements.txt

**Resolution**:
include something like:
`django-simple-captcha>=0.3.4`
in requirements.txt.

patch file:

```
7a8
> django-simple-captcha>=0.3.4
```

**Comment by lampslave** [comment]
Fixed in 2e0f372255f9d3ae47b9dda81434db944c66816c
Thank you from 2017 :)
